### ISSUE TITLE
Is there any way to export metrics on a different port?

### ISSUE THREAD

**Issue by ohmycto** [yabeda-rb/yabeda-puma-plugin#10]
Hi there, first of all thanks for awesome tool!

I use clustered Puma in production and Sidekiq and I want to export metrics on a different port. I've included the following gems into my Gemfile:
```
gem 'yabeda-prometheus-mmap'
gem 'yabeda-puma-plugin'
gem 'yabeda-rails', '~> 0.5.0'
gem 'yabeda-sidekiq', '~> 0.5.0'
```
After that and a bit of configuration everything worked like a charm and I got my metrics visible on port `myapp:3000/metrics`.

Now I want to change the port my metrics are being exposed on. So I put the following variable into my Docker container environment: `PROMETHEUS_EXPORTER_PORT=9394`.

After that Sidekiq exporter has really switched to that port, but Puma metrics are still exposed on 3000. How can I deal with it?

Thanks!

**Comment by Envek** [comment]
Hi! I was able to do it by explicitly running Prometheus exporter in `config/puma.rb` like this:
```ruby
activate_control_app
plugin :yabeda

prometheus_exporter = Puma::Server.new Yabeda::Prometheus::Exporter.rack_app
prometheus_exporter.min_threads = 0
prometheus_exporter.max_threads = 1
host = ENV.fetch("PROMETHEUS_EXPORTER_BIND", "0.0.0.0")
port = ENV.fetch("PROMETHEUS_EXPORTER_PORT", ENV.fetch("PORT", 9394).to_i + 1)
puts "* Starting Yabeda prometheus exporter on #{host}:#{port}"
prometheus_exporter.add_tcp_listener(host, port)
prometheus_exporter.run
```

So it's kind of another Puma inside your Puma (“yo dawg” meme goes here).

However, I doesn't feel reliable for me as I can't be sure that if prometheus exporter will die, then will it be restarted by main Puma process or what. May be there are some hooks in Puma that I'm not aware of.

**Comment by ohmycto** [comment]
Thank you @Envek for your hint. This creates a new endpoint on a custom port, but old endpoint is still available. My point is to remove metrics from default Puma port.

**Comment by ohmycto** [comment]
It looks like @jwhitcraft is trying to implement this in their fork: https://github.com/jwhitcraft/yabeda-puma-plugin/tree/prometheus_server. I've tried this and it works, but `myapp:9394/metrics` returns an empty page. I had no time to dig deeper...

**Comment by Envek** [comment]
Hm, may be you have set up metrics export in your app? Check `config.ru` or `config/routes.rb` files.

For example in Rails you may have added following line in `config/routes.rb`:

```ruby
mount Yabeda::Prometheus::Exporter => "/metrics"
```

Or you may have added this into your `config.ru`:
```ruby
use Yabeda::Prometheus::Exporter
```

Try to remove such lines.

**Comment by jwhitcraft** [comment]
@ohmycto yes, that is the same problem we are having, and i'm unsure as to why right now.

For now we've migrated back to just using basic-auth on the url with nginx.  But as i find time, I'd like to try and get it working.

**Comment by ohmycto** [comment]
@Envek my bad! It was `use Yabeda::Prometheus::Exporter` in `config.ru`! Now everything works like a charm, thanks dude!

@jwhitcraft, @Envek 's solution above works, but still can have some issues.

**Comment by jwhitcraft** [comment]
@ohmycto can you elaborate on the issues, i'm currently just seeing a blank page when i goto `http://0.0.0.0:9395/metrics` while using the code from above and starting puma with 2+ workers (`puma -w 2`)

**Comment by Envek** [comment]
@jwhitcraft, oh, Puma's [clustered mode](https://github.com/puma/puma#clustered-mode) requires extra effort due to the fact that by default metrics are stored in-memory per-process (so puma worker metrics are not available in master process).

To work around that either enable [prometheus-client's `DirectFileStore`](https://github.com/yabeda-rb/yabeda-prometheus/#multi-process-server-support) or use [`yabeda-prometheus-mmap` gem](https://github.com/yabeda-rb/yabeda-prometheus-mmap).

**Comment by jwhitcraft** [comment]
@Envek that is what i'm using:

puma.rb
```ruby 
require 'yabeda/prometheus/exporter'
require 'yabeda/prometheus/mmap'
prometheus_exporter = Puma::Server.new Yabeda::Prometheus::Exporter.rack_app
prometheus_exporter.min_threads = 0
prometheus_exporter.max_threads = 1
host = ENV.fetch("PROMETHEUS_EXPORTER_BIND", "0.0.0.0")
port = ENV.fetch("PROMETHEUS_EXPORTER_PORT", ENV.fetch("PORT", 9394).to_i + 1)
puts "* Starting Yabeda prometheus exporter on #{host}:#{port}"
prometheus_exporter.add_tcp_listener(host, port)
prometheus_exporter.run
```


Gemfile
```ruby
gem 'yabeda-graphql'
gem 'yabeda-http_requests'
gem 'yabeda-prometheus-mmap'
gem 'yabeda-puma-plugin'
gem 'yabeda-rails', '~> 0.5.0'
gem 'yabeda-sidekiq', '~> 0.5.0'
```

**Comment by Envek** [comment]
Hm, weird. @dsalahutdinov, do you have any ideas?

**Comment by ohmycto** [comment]
@jwhitcraft I think you forgot these two in `config/puma.rb`:
```ruby
activate_control_app
plugin :yabeda

# and all your code goes here
```

**Comment by jwhitcraft** [comment]
@ohmycto i have that right above it:

```ruby
# metrics
activate_control_app
plugin :yabeda

require 'yabeda/prometheus/exporter'
require 'yabeda/prometheus/mmap'
prometheus_exporter = Puma::Server.new Yabeda::Prometheus::Exporter.rack_app
prometheus_exporter.min_threads = 0
prometheus_exporter.max_threads = 1
host = ENV.fetch("PROMETHEUS_EXPORTER_BIND", "0.0.0.0")
port = ENV.fetch("PROMETHEUS_EXPORTER_PORT", ENV.fetch("PORT", 9394).to_i + 1)
puts "* Starting Yabeda prometheus exporter on #{host}:#{port}"
prometheus_exporter.add_tcp_listener(host, port)
prometheus_exporter.run
```

**Comment by Envek** [comment]
@jwhitcraft, I tried to replicate your setup in a not-yet-monitored app: copied gems into `Gemfile` in that same order, copied your `config/puma.rb` contents to the end of mine's, run the app with `bundle exec puma -w 2` and it just works like a charm: I can see some basic Puma metrics even before workers fully started. And all metrics appears when there are some requests to application was done.

I wonder whether there are some problems with memory-mapped files creation or anything. Try to adjust `prometheus_multiproc_dir` enviironment variable (see [the `prometheus-client-mmap` gem docs](https://gitlab.com/gitlab-org/prometheus-client-mmap#memory-mapped-files-storage-location)). Or try to disable Puma clustered mode altogether and switch back to official Prometheus client (just to hunt roots of this problem)

**Comment by Envek** [comment]
By the way, do you want to create a pull request with [your prometheus exporter as puma plugin](https://github.com/yabeda-rb/yabeda-puma-plugin/compare/master...jwhitcraft:prometheus_server#diff-160787f6544c9db2eb1e64c6cf4a134c) implementation? I will be glad to merge it. Or I can just commit it on your behalf ;-)

**Comment by jwhitcraft** [comment]
@Envek i'll play around with it later today and report back.

**Comment by jwhitcraft** [comment]
@Envek see #11, also, the app i'm trying to run only ever runs in `single mode` as it's in containers.  I still have one app that doesn't but i'll try and figure this that out when i get to that app.

**Comment by ohmycto** [comment]
This doesn't make sense anymore after release 0.4.0. Thanks, folks!
