### ISSUE TITLE
Getting empty metrics with Padrino app

### ISSUE THREAD

**Issue by rpradeepam** [yabeda-rb/yabeda-puma-plugin#17]
Hello. 
I was trying to setup metrics for a Padrino app on Puma with the following configuration

```
Gemfile

ruby '2.4.6'
...
...

gem 'yabeda-puma-plugin'
gem 'yabeda-prometheus-mmap'
```

```
puma.rb

threads min_threads_count, max_threads_count

preload_app!

activate_control_app
plugin :yabeda
plugin :yabeda_prometheus
```

```
config.ru

require 'yabeda/prometheus/mmap'
use Yabeda::Prometheus::Exporter, path: "/metrics"
...
...
run Padrino.application
```
But `GET http://localhost:9394/metrics` returns an empty response.

Have I missed something here?

**Comment by Envek** [comment]
One quick guess is that you need to execute `Yabeda.configure!` when your application is initialized.

See https://github.com/yabeda-rb/yabeda#usage

In case of Ruby on Rails yabeda does it automatically via [bundled railtie](https://github.com/yabeda-rb/yabeda/blob/master/lib/yabeda/railtie.rb).

**Comment by rpradeepam** [comment]
Yes. That was it. Thank you very much.

**Comment by wvengen** [comment]
Somehow I still need to execute `Yabeda.configure!` manually with version 0.6.0, with a multiprocess puma, `DirectFileStore` and the metrics service running on a diferent port. Only when running `bundle exec puma` (not with `rails s`)
