### ISSUE TITLE
Puma exporter does not works with rails exporter / prometheus-client-mmap

### ISSUE THREAD

**Issue by phumberdroz** [yabeda-rb/yabeda-puma-plugin#2]
Hey,

first thanks for the work you put into this project.

I tried this out today and noticed that the puma plugin is not working with `prometheus-client-mmap`

It just does not report anything on the metrics url then

**Comment by dsalahutdinov** [comment]
Hey, @phumberdroz Thank you for the issue. I will see it.
It is probably connected with the https://github.com/yabeda-rb/yabeda-prometheus/issues/4

Do you have the time to find out the problem by yourself and send the PR?

**Comment by phumberdroz** [comment]
I would but I am sadly just a DevOps Engineer and not too familiar with ruby. Since it works with the normal client I am happy to just use that one.

**Comment by dsalahutdinov** [comment]
Hey, @phumberdroz the original issue is fixed. Bu following this comment you could fix it https://github.com/yabeda-rb/yabeda-rails/issues/5#issuecomment-503713608
