### ISSUE TITLE
Standalone exporter crashes puma on phased restart

### ISSUE THREAD

**Issue by botimer** [yabeda-rb/yabeda-puma-plugin#22]
## Summary 
When running in clustered mode with a standalone port for the Prometheus exporter, phased restarts cause the parent puma process to crash because a new server attempts to start without stopping the previous. Attempting to bind the port raises an error that unrolls the whole thing.

This is because the event/state handling of the embedded server instance doesn't catch the restarts properly. See [yabeda_prometheus.rb](https://github.com/yabeda-rb/yabeda-puma-plugin/blob/59d6ad30ce0fdb6e410e383905c841396f446563/lib/puma/plugin/yabeda_prometheus.rb#L40-L44).

## Expected Behavior

 * Application survives a phased restart
 * Metrics are available before and after restart

## Reproduction Steps

 * Change to the spec/configs directory
 * Add `plugin :yabeda_prometheus` to puma.rb
 * Start app with `puma -C puma.rb lobster.ru`
 * Send SIGUSR1 to the parent puma process (`kill -SIGUSR1 <pid>`)
 * Observe crash: `Errno::EADDRINUSE: Address already in use - bind(2) for "0.0.0.0" port 9394`

**Comment by Envek** [comment]
Fix released in [0.7.0](https://github.com/yabeda-rb/yabeda-puma-plugin/releases/tag/v0.7.0)
