### ISSUE TITLE
Feature proposal: Extract Yabeda configuration

### ISSUE THREAD

**Issue by etrejos** [yabeda-rb/yabeda-puma-plugin#29]
# Overview

Hi. I'd like to be able to register the Yabeda::Puma collector outside of a Puma plugin,
in order to collect Puma metrics without depending on Puma or the `yabeda_prometheus`
Puma plugin.

This is my use case:

I have a Rails application that uses Puma as the web server.
I've enabled the control app and I'm specifying the URL and auth token myself.
I have a separate process, which runs independently from the main application,
which is a simple Rack application that exports the traces collected by the app.

I've been able to export all the metrics collected by the app, however, Puma's
metrics are never collected.

I found that if I run the `Yabeda.configure do end` block found here
https://github.com/yabeda-rb/yabeda-puma-plugin/blob/65531645c3220640ebdceb020475a0873a144a9f/lib/puma/plugin/yabeda.rb#L15
with a few adjustments, I can get accurate Puma metrics in the `/metrics` endpoint.

Please let me know if I'm on the right track or if there's something I'm missing.

# Proposal

I think the `Yabeda.configure` block can be extracted, similar to what the `yabeda-rails`
does offering this method `Yabeda::Rails.install!`:

https://github.com/yabeda-rb/yabeda-rails/blob/3874b3c6a938ee2451a9e4975f7839931708f7af/lib/yabeda/rails.rb#L29

If possible, I'd like that method to accept options, including one called `clustered`
that indicates if Puma is running in clustered mode.

This method can then be called by `lib/puma/plugin/yabeda.rb`.

I can create a PR with this change if what I'm proposing makes sense.

Let me know your thoughts. Thank you!

**Comment by Envek** [comment]
Hey, thanks for detailed explanation.

Probably no one had requirement to collect Puma metrics from outside of Puma (usually in that case collected metrics are shared between processes using e.g. prometheus client direct file storage, see https://github.com/yabeda-rb/yabeda-prometheus#multi-process-server-support, or using alternative yabeda-prometheus-mmap).

For me your use case sounds pretty legit, please make a pull request!

**Comment by etrejos** [comment]
Hi @Envek. Thank you for your reply. I've created the PR. I'll be more than happy to make any changes that you want.

**Comment by etrejos** [comment]
We ended up not needing this change.
