### ISSUE TITLE
Setting up a TCP socket for Puma control app breaks metrics pull

### ISSUE THREAD

**Issue by mazzy89** [yabeda-rb/yabeda-puma-plugin#4]
I've tried to use a TCP socket for the Puma control app but when I set it up the `/metrics` endpoint breaks and it does not return any more metrics.

According to the implementation here https://github.com/yabeda-rb/yabeda-puma-plugin/blob/master/lib/yabeda/puma/plugin/statistics/fetcher.rb this is not possible. Am I reading right?

**Comment by dsalahutdinov** [comment]
Hey @mazzy89 . Thanks for reaching out!
You are right. I think we have to provide a way to work with tpc socket. Are you able to fix it out and send a PR?

**Comment by mazzy89** [comment]
Hi @dsalahutdinov not a Ruby developer here but I can give a try and see what we get here

**Comment by mazzy89** [comment]
PR created here https://github.com/yabeda-rb/yabeda-puma-plugin/pull/5

**Comment by mazzy89** [comment]
Merged to master. Thank you @dsalahutdinov. will you push out the release?

**Comment by dsalahutdinov** [comment]
@mazzy89 Thanks! Here we are https://rubygems.org/gems/yabeda-puma-plugin/versions/0.2.0
