### ISSUE TITLE
TCP socket supports broken

### ISSUE THREAD

**Issue by mazzy89** [yabeda-rb/yabeda-puma-plugin#6]
Unfortunately I broke the plugin

![image](https://user-images.githubusercontent.com/5463218/70709012-2b1e2480-1cdc-11ea-9ace-d953a708e8a9.png)

Missing the reeason. need to investigate

**Comment by dsalahutdinov** [comment]
Hey! Do not worry,  I will fix it soon

**Comment by mazzy89** [comment]
@dsalahutdinov thanks a lot. let me know if I can help here anyhow ;-)

**Comment by mazzy89** [comment]
Thanks a lot. now it works. closing.
