### ISSUE TITLE
Yabeda::Prometheus::Adapter::UndeclaredMetricTags is thrown on /metrics

### ISSUE THREAD

**Issue by dmarszal** [yabeda-rb/yabeda-puma-plugin#9]
Using recent Yabeda gems

yabeda (0.3.0)
yabeda-prometheus (0.2.0, 0.1.5)
yabeda-puma-plugin (0.2.1)

Yabeda::Prometheus::Adapter::UndeclaredMetricTags is thrown on /metrics

Its required to pass :index tag as default within your code

      Yabeda.configure do
        default_tag :index, 0
      end

Should probably be fixed in lib/puma/plugin/yabeda.rb by adding 

default_tag :index, 0

after metrics definition

**Comment by Envek** [comment]
Released yabeda-puma-plugin 0.3.0 where it should be fixed. Please check it.

**Comment by slim1979** [comment]
привет!
я отловил такую же ошибку

```ruby
    prometheus-client (2.1.0)
   yabeda-prometheus (0.6.2)
      prometheus-client (>= 0.10, < 3.0)
      rack
      yabeda (~> 0.5)
    yabeda-puma-plugin (0.6.0)
      json
      puma
      yabeda (~> 0.5)
    yabeda-rails (0.7.2)
      rails
      yabeda (~> 0.8)
    yabeda-sidekiq (0.1.4)
      sidekiq
```
логи

```ruby 
app_1      | Yabeda::Prometheus::Adapter::UndeclaredMetricTags excluded from capture: No public_key specified, no project_id specified
app_1      |   
app_1      | Yabeda::Prometheus::Adapter::UndeclaredMetricTags (Prometheus requires all used tags to be declared at metric registration time. Please add `tags` option to the declaration of metric `sidekiq_jobs_enqueued_total`. Error: labels must have the same signature (keys given: [:queue, :worker] vs. keys expected: []):

```

**Comment by Envek** [comment]
@slim1979 Update yabeda-sidekiq to `~> 0.2` (current version is 0.8)
